name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_nbextensions
  - jupyterlab
  - ipywidgets=7.5.1
  - nodejs
  - numpy
  - opencv
  - libgl1-mesa-glx # only needed for the binder docker to run
  - pandas
  - python=3.7.6
  - scikit-learn
  - seaborn
  - tensorflow
  - widgetsnbextension
  - pip
  - pip:
    - jupyterlab-server
    - nbdime
