name: python37
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pyopengl
  - opencv=4.2.0
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tensorflow
  - jupyter_contrib_nbextensions
  - jupyterlab
  - ipywidgets=7.5.1
  - widgetsnbextension
  - nodejs
  - pip
  - pip:
    - jupyterlab-server
    - nbdime