name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_nbextensions
  - jupyterlab
  - ipywidgets=7.5.1
  - nodejs
  - numpy
  - mesalib # provides an open source implementation of OpenGL needed by 
  - opencv=4.2.0
  - pandas
  - python=3.7.6
  - scikit-learn
  - seaborn
  - tensorflow
  - widgetsnbextension
  - pip
  - pip:
    - jupyterlab-server
    - nbdime
