name: python37
channels:
#  - conda-forge # removed this channel to eliminate an error running opencv on
# a binder docker. The error was due to a dependency on openGL that was not supported
# on the binderhub docker. Aparently, then conda version of opencv is different
# and does not require opencv??
  - defaults
dependencies:
  - numpy
  - opencv
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tensorflow
  - jupyter_contrib_nbextensions
  - jupyterlab
  - ipywidgets==7.5.1
  - widgetsnbextension
  - nodejs
  - pip
  - pip:
    - jupyterlab-server
    - nbdime